site_name: Guy
site_description: Simple GUI (using chrome) for python

theme:
    name: 'material'
    palette:
        primary: 'purple'
        accent: 'purple'

repo_name: manatlan/guy
repo_url: https://github.com/manatlan/guy
edit_uri: ""

nav:
    - Introduction: 'index.md'
    - Example: 'simplest.md'
    - Anatomy: anatomy.md
    - Server side: server.md
    - Client side: client.md
    - Multiple Instance: multiple.md
    - Run guy's app: run.md
    - How-to:
        - wuy to guy: howto_migrate_from_wuy_to_guy.md
        - freeze exe/windows: howto_build_exe_windows.md
        - Produce an APK/android: howto_build_apk_android.md
markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false
  - admonition      